apiVersion: v1
kind: Service
metadata:
  name: new-name-1
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32766
  - port: 90
    targetPort: 90
    nodePort: 32767
  type: NodePort
  selector:
    app: myapp
