apiVersion: apps/v1
kind: Deployment
metadata:
  name: landon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landon-app
  template:
    metadata:
      labels:
        app: landon-app
    spec:
      containers:
      - image: docker.io/beaconfireiic/simple-spring-test:1.0.0-1-dev
        name: landon-app
        ports:
        - containerPort: 8080
