apiVersion: apps/v1
kind: Deployment
metadata:
  name: landon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landon-app
  template:
    metadata:
      labels:
        app: landon-app
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/public-namespace/myapp:v1
        name: landon-app
        ports:
        - containerPort: 80
